/**
 * Safety gate for SQL generated by the LLM. Enforces:
 *  - Single statement, SELECT or WITH only
 *  - Must reference the whitelisted operational table
 *  - No DML/DDL keywords, no semicolons, no BigQuery scripting
 *  - Adds a LIMIT clause if absent
 *  - Rejects queries without a bounded date filter (guards against full-table scans)
 *
 * Defense in depth: BigQuery credentials are also scoped to read-only data viewer,
 * so a bypass here still can't mutate data — this just keeps garbage out.
 */

const ALLOWED_TABLE_REF = 'an_operational_dash';

const FORBIDDEN_KEYWORDS = [
  'insert', 'update', 'delete', 'drop', 'create', 'alter', 'truncate',
  'merge', 'grant', 'revoke', 'execute', 'call', 'declare', 'begin',
  'load', 'export', 'copy', 'rename',
];

const MAX_ROWS = 100;
const MAX_DATE_RANGE_DAYS = 400; // ~13 months — enough for YoY questions

export interface SqlSafetyResult {
  ok: boolean;
  sql: string;
  error?: string;
}

export function validateAndHardenSql(rawSql: string): SqlSafetyResult {
  let sql = rawSql.trim();

  // Strip trailing semicolon(s) and any whitespace
  sql = sql.replace(/;+\s*$/g, '').trim();

  if (!sql) {
    return { ok: false, sql, error: 'Empty SQL.' };
  }

  // No internal semicolons → single statement only
  if (sql.includes(';')) {
    return { ok: false, sql, error: 'Only a single statement is allowed (found `;`).' };
  }

  // Strip comments for keyword scanning (keep original for execution)
  const scan = sql
    .replace(/--[^\n]*/g, '')
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .toLowerCase();

  // Must start with SELECT or WITH
  if (!/^\s*(select|with)\b/.test(scan)) {
    return { ok: false, sql, error: 'Only SELECT / WITH queries are allowed.' };
  }

  // Reject forbidden keywords as whole words
  for (const kw of FORBIDDEN_KEYWORDS) {
    const re = new RegExp(`\\b${kw}\\b`, 'i');
    if (re.test(scan)) {
      return { ok: false, sql, error: `Forbidden keyword detected: \`${kw.toUpperCase()}\`.` };
    }
  }

  // Must reference the operational table
  if (!scan.includes(ALLOWED_TABLE_REF)) {
    return { ok: false, sql, error: `Query must read from \`${ALLOWED_TABLE_REF}\`.` };
  }

  // Must have a date filter — the table has 12+ years of history, so unbounded
  // queries are disasters. Accept `date =` (single day), `date BETWEEN`, `date >=`,
  // `date >`, `date IN`. Single-day equality is safe since it binds to one date.
  if (!/\bdate\s*(=|>=|>|between|in\s*\()/i.test(scan)) {
    return {
      ok: false,
      sql,
      error: 'Query must filter by `date` (use `date =`, `date BETWEEN`, or `date >=`).',
    };
  }

  // Enforce max date range if BETWEEN is used with literal dates we can parse
  const betweenMatch = sql.match(
    /\bdate\s+between\s+(?:date\s+)?'(\d{4}-\d{2}-\d{2})'\s+and\s+(?:date\s+)?'(\d{4}-\d{2}-\d{2})'/i
  );
  if (betweenMatch) {
    const [, s, e] = betweenMatch;
    const diffDays = Math.abs(
      (new Date(e).getTime() - new Date(s).getTime()) / (1000 * 60 * 60 * 24)
    );
    if (diffDays > MAX_DATE_RANGE_DAYS) {
      return {
        ok: false,
        sql,
        error: `Date range (${Math.round(diffDays)}d) exceeds max ${MAX_DATE_RANGE_DAYS}d.`,
      };
    }
  }

  // Ensure a LIMIT. Add one if absent; lower it if it's too high.
  const limitMatch = sql.match(/\blimit\s+(\d+)\b/i);
  if (!limitMatch) {
    sql = `${sql}\nLIMIT ${MAX_ROWS}`;
  } else {
    const existing = parseInt(limitMatch[1], 10);
    if (existing > MAX_ROWS) {
      sql = sql.replace(/\blimit\s+\d+\b/i, `LIMIT ${MAX_ROWS}`);
    }
  }

  return { ok: true, sql };
}
